# Generated by Django 5.1.4 on 2024-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_address', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('land_price', models.FloatField()),
                ('property_pid', models.IntegerField()),
                ('physical_survey_number', models.IntegerField()),
                ('ipfs_hash', models.CharField(max_length=255)),
                ('document_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandInspector',
            fields=[
                ('inspector_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_address', models.CharField(max_length=42, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('lands_owned', models.TextField()),
                ('document_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
