# Generated by Django 5.1.4 on 2024-12-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0002_buyer_status_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='pwd',
            field=models.CharField(default='abc', max_length=12),
        ),
        migrations.AddField(
            model_name='landinspector',
            name='pwd',
            field=models.CharField(default='abc', max_length=12),
        ),
        migrations.AddField(
            model_name='seller',
            name='pwd',
            field=models.CharField(default='abc', max_length=12),
        ),
    ]
