# Generated by Django 5.1.4 on 2024-12-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0003_buyer_pwd_landinspector_pwd_seller_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinspector',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
