# Generated by Django 5.1.4 on 2024-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0006_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=12, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
